services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: manager
      POSTGRES_DB: tutorialseguranca

volumes:
  db:
    driver: local